version: "3.8"

services:
  # FastAPI
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=nike
      - MYSQL_USER=root
      - MYSQL_PASSWORD=10051998
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_HOST=redis
    networks:
      - backend

  # Redis
  redis:
    image: "redis:alpine"
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  # Queue
  # queue:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.queue
  #   container_name: queue
  #   ports:
  #     - "9000:9000"
  #   networks:
  #     - backend

  # Worker
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker
    restart: always
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  # Celery_beat
  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: celery_beat
    restart: always
    depends_on:
      - worker
    command: ["celery", "-A", "worker", "beat", "--loglevel=info"]

  # MySQL
  mysql:
    image: mysql:8.0
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 10051998
      MYSQL_DATABASE: nike
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

# Network and volume
networks:
  backend:
    driver: bridge

volumes:
  mysql-data:
