# Generated by Django 5.1.6 on 2025-02-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_product_customer_orderplaced_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
