# Generated by Django 5.1.6 on 2025-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_news_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('Deleted', 'Deleted'), ('Hidden', 'Hidden'), ('Active', 'Active'), ('Save', 'Save')], default='Active', max_length=10),
        ),
    ]
