# Generated by Django 5.1.6 on 2025-02-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_new_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(null=True, upload_to='news_images/'),
        ),
    ]
