"""add multiple choice support

Revision ID: c90942cedb23
Revises: d1a500fe996f
Create Date: 2026-07-15 22:42:40.891876

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c90942cedb23"
down_revision: str | Sequence[str] | None = "d1a500fe996f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("option_order_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["study_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "session_id", "question_id", name="uq_question_deliveries_session_question"
        ),
    )
    with op.batch_alter_table("question_deliveries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_deliveries_question_id"), ["question_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_deliveries_session_id"), ["session_id"], unique=False
        )

    op.create_table(
        "question_options",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("normalized_content", sa.String(length=500), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column("auto_generated", sa.Boolean(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "length(trim(content)) > 0", name="ck_question_options_content_nonempty"
        ),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_options", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_options_normalized_content"),
            ["normalized_content"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_question_options_question_id"), ["question_id"], unique=False
        )
        batch_op.create_index(
            "ux_question_options_one_correct",
            ["question_id"],
            unique=True,
            sqlite_where=sa.text("is_correct = 1"),
            postgresql_where=sa.text("is_correct = true"),
        )

    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("selected_option_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("correct_option_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("is_correct", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("answer_order_json", sa.Text(), nullable=True))
        batch_op.alter_column("submitted_answer", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("normalized_answer", existing_type=sa.TEXT(), nullable=True)
        batch_op.alter_column("evaluation_json", existing_type=sa.TEXT(), nullable=True)
        batch_op.create_foreign_key(
            "fk_attempts_selected_option_id",
            "question_options",
            ["selected_option_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            "fk_attempts_correct_option_id",
            "question_options",
            ["correct_option_id"],
            ["id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("question_progress", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("incorrect_count", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("accuracy", sa.Float(), nullable=False, server_default="0"))
        batch_op.add_column(
            sa.Column("current_correct_streak", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("best_correct_streak", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(sa.Column("last_is_correct", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("last_selected_option_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_question_progress_last_selected_option_id",
            "question_options",
            ["last_selected_option_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # Existing (pre-multiple-choice) questions are backfilled as FREE_TEXT so they keep
    # working exactly as before via /evaluate; only newly-created rows default to
    # MULTIPLE_CHOICE (that default lives in the ORM model, applied on INSERT).
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "question_format",
                sa.Enum(
                    "MULTIPLE_CHOICE",
                    "FREE_TEXT",
                    "CODE",
                    "SQL",
                    name="questionformat",
                    native_enum=False,
                    length=20,
                ),
                nullable=False,
                server_default="FREE_TEXT",
            )
        )
        batch_op.add_column(
            sa.Column("needs_review", sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_column("needs_review")
        batch_op.drop_column("question_format")

    with op.batch_alter_table("question_progress", schema=None) as batch_op:
        batch_op.drop_constraint("fk_question_progress_last_selected_option_id", type_="foreignkey")
        batch_op.drop_column("last_selected_option_id")
        batch_op.drop_column("last_is_correct")
        batch_op.drop_column("best_correct_streak")
        batch_op.drop_column("current_correct_streak")
        batch_op.drop_column("accuracy")
        batch_op.drop_column("incorrect_count")

    with op.batch_alter_table("attempts", schema=None) as batch_op:
        batch_op.drop_constraint("fk_attempts_correct_option_id", type_="foreignkey")
        batch_op.drop_constraint("fk_attempts_selected_option_id", type_="foreignkey")
        batch_op.alter_column("evaluation_json", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("normalized_answer", existing_type=sa.TEXT(), nullable=False)
        batch_op.alter_column("submitted_answer", existing_type=sa.TEXT(), nullable=False)
        batch_op.drop_column("answer_order_json")
        batch_op.drop_column("is_correct")
        batch_op.drop_column("correct_option_id")
        batch_op.drop_column("selected_option_id")

    with op.batch_alter_table("question_options", schema=None) as batch_op:
        batch_op.drop_index(
            "ux_question_options_one_correct",
            sqlite_where=sa.text("is_correct = 1"),
            postgresql_where=sa.text("is_correct = true"),
        )
        batch_op.drop_index(batch_op.f("ix_question_options_question_id"))
        batch_op.drop_index(batch_op.f("ix_question_options_normalized_content"))

    op.drop_table("question_options")
    with op.batch_alter_table("question_deliveries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_deliveries_session_id"))
        batch_op.drop_index(batch_op.f("ix_question_deliveries_question_id"))

    op.drop_table("question_deliveries")
    # ### end Alembic commands ###
