"""initial schema

Revision ID: d1a500fe996f
Revises:
Create Date: 2026-07-15 22:09:03.123285

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1a500fe996f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_categories_slug"),
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=False)
    op.create_table(
        "import_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "DOCX",
                "PASTED_TEXT",
                "MANUAL",
                "SEED",
                "API",
                name="sourcetype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PARSING",
                "VALIDATING",
                "COMPLETED",
                "FAILED",
                name="importstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column(
            "duplicate_strategy",
            sa.Enum(
                "SKIP",
                "UPDATE",
                "CREATE_COPY",
                name="duplicatestrategy",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("summary_json", sa.Text(), nullable=True),
        sa.Column("warnings_json", sa.Text(), nullable=True),
        sa.Column("errors_json", sa.Text(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "questions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column(
            "question_type",
            sa.Enum(
                "TEXT", "CODE", "SQL", "SCENARIO", name="questiontype", native_enum=False, length=20
            ),
            nullable=False,
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("reference_answer", sa.Text(), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column(
            "difficulty",
            sa.Enum("EASY", "MEDIUM", "HARD", name="difficulty", native_enum=False, length=20),
            nullable=False,
        ),
        sa.Column(
            "language_scope",
            sa.Enum(
                "GENERAL",
                "JAVA",
                "PYTHON",
                "SQL",
                name="languagescope",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("java_answer", sa.Text(), nullable=True),
        sa.Column("python_answer", sa.Text(), nullable=True),
        sa.Column("sql_answer", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "source_type",
            sa.Enum(
                "DOCX",
                "PASTED_TEXT",
                "MANUAL",
                "SEED",
                "API",
                name="sourcetype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("source_name", sa.String(length=255), nullable=True),
        sa.Column("source_order", sa.Integer(), nullable=True),
        sa.Column("minimum_answer_length", sa.Integer(), nullable=False),
        sa.Column("minimum_token_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_questions_category_id"), "questions", ["category_id"], unique=False)
    op.create_index(op.f("ix_questions_content_hash"), "questions", ["content_hash"], unique=False)
    op.create_table(
        "study_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum(
                "RANDOM",
                "CATEGORY",
                "REVIEW",
                "EXAM",
                name="studymode",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "language_scope",
            sa.Enum(
                "GENERAL",
                "JAVA",
                "PYTHON",
                "SQL",
                name="languagescope",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("total_questions", sa.Integer(), nullable=False),
        sa.Column("answered_questions", sa.Integer(), nullable=False),
        sa.Column("total_score", sa.Float(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_study_sessions_user_id"), "study_sessions", ["user_id"], unique=False)
    op.create_table(
        "answer_concepts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("auto_generated", sa.Boolean(), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("weight >= 0", name="ck_answer_concepts_weight_nonneg"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_answer_concepts_question_id"), "answer_concepts", ["question_id"], unique=False
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("submitted_answer", sa.Text(), nullable=False),
        sa.Column("normalized_answer", sa.Text(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column(
            "classification",
            sa.Enum(
                "CORRECT",
                "MOSTLY_CORRECT",
                "PARTIALLY_CORRECT",
                "INCORRECT",
                name="classification",
                native_enum=False,
                length=30,
            ),
            nullable=False,
        ),
        sa.Column("evaluation_json", sa.Text(), nullable=False),
        sa.Column("response_time_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["session_id"], ["study_sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_attempts_question_id"), "attempts", ["question_id"], unique=False)
    op.create_index(op.f("ix_attempts_session_id"), "attempts", ["session_id"], unique=False)
    op.create_table(
        "contradiction_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("penalty", sa.Float(), nullable=False),
        sa.Column("maximum_score", sa.Float(), nullable=True),
        sa.Column(
            "match_type",
            sa.Enum(
                "EXACT",
                "CONTAINS",
                "FUZZY",
                "ALIAS",
                name="matchtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("minimum_similarity", sa.Float(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "maximum_score IS NULL OR (maximum_score >= 0 AND maximum_score <= 100)",
            name="ck_contradiction_rules_max_score_range",
        ),
        sa.CheckConstraint("penalty >= 0", name="ck_contradiction_rules_penalty_nonneg"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_contradiction_rules_question_id"),
        "contradiction_rules",
        ["question_id"],
        unique=False,
    )
    op.create_table(
        "import_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("import_job_id", sa.Integer(), nullable=False),
        sa.Column("source_order", sa.Integer(), nullable=False),
        sa.Column("raw_content", sa.Text(), nullable=False),
        sa.Column("parsed_data_json", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "VALID",
                "WARNING",
                "ERROR",
                "CREATED",
                "UPDATED",
                "SKIPPED",
                name="importitemstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("question_id", sa.Integer(), nullable=True),
        sa.Column("warnings_json", sa.Text(), nullable=True),
        sa.Column("errors_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["import_job_id"], ["import_jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_import_items_import_job_id"), "import_items", ["import_job_id"], unique=False
    )
    op.create_table(
        "question_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("question_id", sa.Integer(), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("correct_count", sa.Integer(), nullable=False),
        sa.Column("average_score", sa.Float(), nullable=False),
        sa.Column("best_score", sa.Float(), nullable=False),
        sa.Column("last_score", sa.Float(), nullable=False),
        sa.Column("mastery_level", sa.String(length=20), nullable=False),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("next_review_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["question_id"], ["questions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_question_progress_next_review_at"),
        "question_progress",
        ["next_review_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_question_progress_question_id"), "question_progress", ["question_id"], unique=False
    )
    op.create_index(
        op.f("ix_question_progress_user_id"), "question_progress", ["user_id"], unique=False
    )
    op.create_table(
        "concept_keywords",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("concept_id", sa.Integer(), nullable=False),
        sa.Column("keyword", sa.String(length=300), nullable=False),
        sa.Column("normalized_keyword", sa.String(length=300), nullable=False),
        sa.Column(
            "match_type",
            sa.Enum(
                "EXACT",
                "CONTAINS",
                "FUZZY",
                "ALIAS",
                name="matchtype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("minimum_similarity", sa.Float(), nullable=False),
        sa.Column("language", sa.String(length=20), nullable=True),
        sa.Column("auto_generated", sa.Boolean(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "minimum_similarity >= 0 AND minimum_similarity <= 100",
            name="ck_concept_keywords_similarity_range",
        ),
        sa.ForeignKeyConstraint(["concept_id"], ["answer_concepts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_concept_keywords_concept_id"), "concept_keywords", ["concept_id"], unique=False
    )
    op.create_index(
        op.f("ix_concept_keywords_normalized_keyword"),
        "concept_keywords",
        ["normalized_keyword"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_concept_keywords_normalized_keyword"), table_name="concept_keywords")
    op.drop_index(op.f("ix_concept_keywords_concept_id"), table_name="concept_keywords")
    op.drop_table("concept_keywords")
    op.drop_index(op.f("ix_question_progress_user_id"), table_name="question_progress")
    op.drop_index(op.f("ix_question_progress_question_id"), table_name="question_progress")
    op.drop_index(op.f("ix_question_progress_next_review_at"), table_name="question_progress")
    op.drop_table("question_progress")
    op.drop_index(op.f("ix_import_items_import_job_id"), table_name="import_items")
    op.drop_table("import_items")
    op.drop_index(op.f("ix_contradiction_rules_question_id"), table_name="contradiction_rules")
    op.drop_table("contradiction_rules")
    op.drop_index(op.f("ix_attempts_session_id"), table_name="attempts")
    op.drop_index(op.f("ix_attempts_question_id"), table_name="attempts")
    op.drop_table("attempts")
    op.drop_index(op.f("ix_answer_concepts_question_id"), table_name="answer_concepts")
    op.drop_table("answer_concepts")
    op.drop_index(op.f("ix_study_sessions_user_id"), table_name="study_sessions")
    op.drop_table("study_sessions")
    op.drop_index(op.f("ix_questions_content_hash"), table_name="questions")
    op.drop_index(op.f("ix_questions_category_id"), table_name="questions")
    op.drop_table("questions")
    op.drop_table("import_jobs")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
